- name: Configure FTP server.
  hosts: ftp
  become: True
  tasks:
    - name: Copy SSH public key
      copy:
        src: ../keys/ssh-key.pub
        dest: /home/vagrant/.ssh/authorized_keys
        mode: '0600'
        owner: vagrant
        group: vagrant
    - name: Install FTP package.
      ansible.builtin.package:
        update_cache: True
        apt:
         - ftp


