- name: Configure FTP server.
  hosts: ftp
  become: True
  tasks:
    - name: Copy SSH public key
      copy:
        src: ../keys/ssh-key.pub
        dest: /home/vagrant/.ssh/authorized_keys
        mode: '0600'
        owner: vagrant
        group: vagrant

    - name: Install FTP package
      ansible.builtin.package:
        update_cache: yes
        name: vsftpd

    - name: Install dependencies to obtain SSL certificate
      ansible.builtin.package:
        update_cache: yes
        name: python3-cryptography 

    - name: Install passlib for password hashing
      ansible.builtin.package:
        update_cache: yes
        name: python3-passlib

    - name: Create vsftpd config directory
      file:
        path: /etc/vsftpd
        state: directory
        owner: root
        group: ftp
        mode: 0750

    - name: Generate SSL Private Key
      openssl_privatekey:
        path: /etc/ssl/private/ssl-cert-priv.key
        size: 2048

    - name: Generate sign request (CSR)
      openssl_csr:
        path: /etc/ssl/private/ssl-sign.csr
        privatekey_path: /etc/ssl/private/ssl-cert-priv.key
        common_name: "ssl-ftp-cert"
        country_name: "ES"
        organization_name: "IZV"
        email_address: "jrodcas899@ieszaidinvergeles.org"

    - name: Obtain SSL public key
      openssl_certificate:
        path: /etc/ssl/certs/ssl-cert-pub.pem
        privatekey_path: /etc/ssl/private/ssl-cert-priv.key
        csr_path: /etc/ssl/private/ssl-sign.csr
        provider: selfsigned

    - name: Copy configuration files 
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
      loop:
        - { src: ../files/ftp/ftp.conf, dest: /etc/vsftpd/ }
        - { src: ../files/ftp/mirror.conf, dest: /etc/vsftpd/ }
        - { src: ../files/ftp/.message, dest: /etc/vsftpd/ }
        - { src: ../files/ftp/vsftpd.chroot_list, dest: /etc/vsftpd/ }
        - { src: ../files/ftp/systemd/vsftpd-mirror.service, dest: /etc/systemd/system/ }
        - { src: ../files/ftp/systemd/vsftpd-ftp.service, dest: /etc/systemd/system/ }

    - name: Disable vsftpd default server
      service:
        name: vsftpd
        enabled: no
        state: stopped

    - name: Enable service for anonymous FTP server
      service:
        name: vsftpd-mirror
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Enable service for local users FTP server
      service:
        name: vsftpd-ftp
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Copy resolv.conf
      copy:
        src: ../files/resolv.conf
        dest: /etc/resolv.conf

    - name: Create local user charles
      user:
        name: charles
        password: "{{ '1234' | password_hash('sha512', 'saltcharles') }}"

    - name: Create local user laura
      user:
        name: laura
        password: "{{ '1234' | password_hash('sha512', 'saltlaura') }}"

   


