- name: Configure FTP server.
  hosts: ftp
  become: True
  tasks:
    - name: Copy SSH public key
      copy:
        src: ../keys/ssh-key.pub
        dest: /home/vagrant/.ssh/authorized_keys
        mode: '0600'
        owner: vagrant
        group: vagrant

    - name: Install FTP package
      ansible.builtin.package:
        update_cache: yes
        name: vsftpd

    - name: Install dependencies to obtain SSL certificate
      ansible.builtin.package:
        update_cache: yes
        name: python3-cryptography 

    - name: Install passlib for password hashing
      ansible.builtin.package:
        update_cache: yes
        name: python3-passlib

    - name: Create vsftpd config directory
      file:
        path: /etc/vsftpd
        state: directory
        owner: root
        group: ftp
        mode: 0750

    - name: Copy resolv.conf
      copy:
        src: ../files/resolv.conf
        dest: /etc/resolv.conf

    - name: Create local user charles
      user:
        name: charles
        password: "{{ '1234' | password_hash('sha512', 'saltcharles') }}"

    - name: Create local user laura
      user:
        name: laura
        password: "{{ '1234' | password_hash('sha512', 'saltlaura') }}"

   


