---
- hosts: all
  tasks:
    - name: Ping test
      ping: 

    - name: Copy SSH public key
      copy:
        src: ../keys/ssh-key.pub
        dest: /home/vagrant/.ssh/authorized_keys
        mode: '0600'
        owner: vagrant
        group: vagrant

