- name: Configure FTP server.
  hosts: ftp
  become: True
  tasks:
    - name: Copy SSH public key
      copy:
        src: ../keys/ssh-key.pub
        dest: /home/vagrant/.ssh/authorized_keys
        mode: '0600'
        owner: vagrant
        group: vagrant

    - name: Install FTP package
      ansible.builtin.package:
        update_cache: True
        apt:
         - vsftps

    - name: Install dependencies to obtain SSL certificate
      ansible.builtin.package:
        update_cache: True
        apt: python3-cryptography 

    - name: Create vsftpd config directory
      file:
        path: /etc/vsftpd
        state: directory
        owner: root
        group: ftp
        mode: 0750

    - name: Generate SSL Private Key
      openssl_privatekey:
        path: /etc/ssl/private/ssl-cert-priv.key
        size: 2048


