- name: Configure FTP server.
  hosts: ftp
  become: true
  tasks:
    - name: Install FTP package
      ansible.builtin.package:
        update_cache: true
        name: vsftpd

    - name: Install dependencies to obtain SSL certificate
      ansible.builtin.package:
        update_cache: true
        name: python3-cryptography

    - name: Create vsftpd config directory
      ansible.builtin.file:
        path: /etc/vsftpd
        state: directory
        owner: root
        group: ftp
        mode: '0750'

    - name: Generate SSL Private Key
      community.crypto.openssl_privatekey:
        path: "{{ ssl_pr }}/ssl-cert-priv.key"
        size: 2048

    - name: Generate sign request (CSR)
      community.crypto.openssl_csr:
        path: "{{ ssl_pr }}ssl-sign.csr"
        privatekey_path: "{{ ssl_pr }}ssl-cert-priv.key"
        common_name: "ssl-ftp-cert"
        country_name: "ES"
        organization_name: "IZV"
        email_address: "jrodcas899@ieszaidinvergeles.org"

    - name: Obtain SSL public key
      community.crypto.x509_certificate:
        path: "{{ ssl }}certs/ssl-cert-pub.pem"
        privatekey_path: "{{ ssl_pr }}ssl-cert-priv.key"
        csr_path: "{{ ssl_pr }}ssl-sign.csr"
        provider: selfsigned

    - name: Copy configuration files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: '0644'
      loop:
        - { src: "{{ ftp_path }}ftp.conf", dest: /etc/vsftpd/ }
        - { src: "{{ ftp_path }}mirror.conf", dest: /etc/vsftpd/ }
        - { src: "{{ ftp_path }}.message", dest: /srv/ftp }
        - { src: "{{ ftp_path }}vsftpd.chroot_list", dest: /etc/vsftpd/ }
        - { src: "{{ ftp_path }}systemd/vsftpd-mirror.service", dest: /etc/systemd/system/ }
        - { src: "{{ ftp_path }}systemd/vsftpd-ftp.service", dest: /etc/systemd/system/ }

    - name: Disable vsftpd default server
      ansible.legacy.service:
        name: vsftpd
        enabled: false
        state: stopped

    - name: Enable service for anonymous FTP server
      ansible.legacy.service:
        name: vsftpd-mirror
        enabled: true
        state: started
        daemon_reload: true

    - name: Enable service for local users FTP server
      ansible.legacy.service:
        name: vsftpd-ftp
        enabled: true
        state: started
        daemon_reload: true

    - name: Copy resolv.conf
      ansible.legacy.copy:
        src: ../files/resolv.conf
        dest: /etc/resolv.conf

    - name: Create local user charles
      ansible.legacy.user:
        name: charles
        password: "{{ pass_c }}"

    - name: Create local user laura
      ansible.legacy.user:
        name: laura
        password: "{{ pass_l }}"
