- name: Configure of DNS Server
  hosts: dns
  become: true
  tasks:
    - name: Install Bind9
      ansible.builtin.package:
        update_cache: true
        name: bind9

    - name: Copy DNS configuration files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: bind
        group: bind
        mode: '0644'
      loop:
        - { src: "{{ dns_path }}named", dest: /etc/default/ }
        - { src: "{{ dns_path }}named.conf.options", dest: /etc/bind/ }
        - { src: "{{ dns_path }}named.conf.local", dest: /etc/bind/ }
        - { src: "{{ dns_path }}db.sri.ies", dest: /var/lib/bind/ }
        - { src: "{{ dns_path }}rev.sri.ies", dest: /var/lib/bind/ }

    - name: Validate DNS configuration
      ansible.builtin.command: named-checkconf
      register: conf_check
      changed_when: false
      failed_when: conf_check.rc != 0

    - name: Restart bind9 service
      ansible.legacy.systemd:
        name: bind9
        enabled: true
        state: restarted
