- name: Configure of DNS Server
  hosts: dns
  become: true
  tasks:
    - name: Install Bind9
      ansible.builtin.package:
        update_cache: yes
        name: bind9

    - name: Copy DNS configuration files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: bind
        group: bind 
      loop:
        - { src: "{{ dns_path }}named", dest: /etc/default/ }
        - { src: "{{ dns_path }}named.conf.options", dest: /etc/bind/ }
        - { src: "{{ dns_path }}named.conf.local", dest: /etc/bind/ }
        - { src: "{{ dns_path }}db.sri.ies", dest: /var/lib/bind/ }
        - { src: "{{ dns_path }}rev.sri.ies", dest: /var/lib/bind/ }

    - name: Copy resolv.conf
      ansible.builtin.copy:
        src: ../files/resolv.conf
        dest: /etc/

    - name: Validate bind9 config
      command: named-checkconf

    - name: Restart bind9 service
      systemd:
        name: bind9
        enabled: true
        state: restarted