name: ansible-lint
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install community.crypto from Ansible galaxy
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint
          ansible-galaxy collection install community.crypto
  
      - name: Run ansible-lint
        run: |
          ansible-lint ansible/
